## new alternative of Numpy library -> array library

In [1]:
import array 

In [4]:
# nums = list (range (0,int(1e2))) #wont implement if list aint written
# nums = list (range (100,600,100))
nums = list (range (0, 10))
nums

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
nums1 = array.array('i', nums)
nums1

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
nums.insert(5, 5.6)
nums
print (nums[5])

5.6


In [14]:
nums_arr = array.array('f', nums)
nums_arr

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.599999904632568, 5.599999904632568, 5.599999904632568, 5.599999904632568, 5.0, 6.0, 7.0, 8.0, 9.0])

In [16]:
nums_arr = array.array('i', nums) #will throw an error -> ''float' object cannot be interpreted as an integer'

TypeError: 'float' object cannot be interpreted as an integer

In [17]:
type (nums_arr[5])

float

In [22]:
# nums_arr.mean ##throw an error

# numpy

In [23]:
import numpy as np

In [30]:
np.array([5, 6, 7, 8]) #passing list as an argument
np.array((5, 6, 7, 8)) #passing tuple as an argument
# np.array(5, 6, 7, 8) #passing tuple as an argument ..........throws an error


array([5, 6, 7, 8])

In [31]:
my_lst = [5, 5, 6, 8]
sorted(my_lst) #temop list
my_lst.sort() #permanent list

In [32]:
np.array(my_lst)

array([5, 5, 6, 8])

In [33]:
np.array([6, 5.6, 8, 8]) #type promotion

array([6. , 5.6, 8. , 8. ])

In [35]:
np.array(['a1', 'b1','c1', 'd1'])
np.array(['a1', 'b1','c1', 'd1'])[0] #array of strings
dir(np.array(['a1', 'b1','c1', 'd1'])[0]) #array of strings

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__iter__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',

In [45]:
np.array([5.3, 6.4, 2.3, 8.6], dtype=np.float16)
np.array([5.3, 6.4, 2.3, 8.6], dtype=np.float32)
# np.array([5.3, 6.4, 2.3, 8.6], dtype=np.float_) #error in new numpy version 2.0 .......
np.array([5.3, 6.4, 2.3, 8.6], dtype=np.float64)
# np.array([5.3, 6.4, 2.3, 8.6], dtype=np.float) #error
# np.array([5.3, 6.4, 2.3, 8.6], dtype=np.float8) #error

array([5.3, 6.4, 2.3, 8.6])

In [52]:
np.zeros(6, dtype= int)

array([0, 0, 0, 0, 0, 0])

In [53]:
np.ones((3,2), dtype= int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [55]:
np.linspace(0,1,5) #endpoint included

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [59]:
 log_space = np.logspace(0, 1, 5, dtype= float) #logarithmic spaced............log10 = 1
log_space

array([ 1.        ,  1.77827941,  3.16227766,  5.62341325, 10.        ])