# We have covered a set of basic concepts of `array` and `NumPy` modules
## Next we move other aspects of NumPy in greater detail.


In [63]:
import numpy as np

<IPython.core.display.Javascript object>

# We generate below random number based arrays in 1,2, 3 dimensions to show important attributes.

# And how to check no of dimensions, size and shape and how to access elements of arrays.


------------------------
------------------------
# Learning NumPy is important because it forms one of the pillars of another useful library called `pandas` (**Pa**nel **D**ata **A**nalysi**s**) .

## Beginners would be puzzled why `NumPy` was needed in the first place. The inventor of Python Guido Van Rossum was using python only for system admininstration (troubleshoot, and maintain computer servers and networks ie, hardware) tasks. He was writing small scripts (one or two line commands only).

## Python script was much more readable than C. So sysadmins in other firms and organisations could easily modify it for their specific tasks.

## Others users of Python thought why not use Python for numerical calculations because it was so English like. That is how NumPy was born in 1995.

## Note that in English we write `NumPy` (camel case) and in python language itself it is written in all small case `numpy`.  
------------------------
------------------------


# https://numpy.org/doc/stable/reference/random/index.html

# From the link above

# The `numpy.random` module implements pseudo-random number generators (PRNGs or RNGs, for short) with the ability to draw samples.


In [64]:
my_rng = np.random.default_rng(seed=2023) # I can specify the seed hence my_rng
my_rng # This is what is called a Bit-Generator

<IPython.core.display.Javascript object>

Generator(PCG64) at 0x7DA5DA9E4580

---
---
<font size = 8 color = red face = Monospace>
my_rng.integers(low = 0, high = 10, size = 7)
</font>

## Here high value will not included by default. So idea of half open interval [1, 10) is applied.

## Here is a way of understanding this :

## From the population of numbers comprising numbers 1 to 10 draw a sample of size 7  
---
---

In [65]:
my_rng = np.random.default_rng(seed=2023) # I can specify the seed hence my_rng
my_rng

<IPython.core.display.Javascript object>

Generator(PCG64) at 0x7DA5DA9E49E0

In [66]:
# rand_1D = my_rng.integers(low = 2, high = 12, size = 7)
rand_1D = my_rng.integers(low = 2, high = 12, size = 50)
print(rand_1D) # from sequence of 10 numbers, draw a sample of 50
# so there will be some repeats

## Every time you run this code cell a new set of random values is generated.
## Please try this yourself.
# Check how may random numbers were generated.
len(rand_1D) # 50 because we specified size = 50 above

<IPython.core.display.Javascript object>

[ 6  2  3  4  4  3  7  6  4  8  2  7  4  9  4  7  6 10  3  3  3  7  5 10
  4  3  7  8  2  4  3 10  5  7  8  6  6  5  9 11 10  9  9  6  3 11  8  6
 10  4]


50


---
---
## We can also write
<font size = 8 color = red face = Monospace>
my_rng.integers(10, size = 7) <br>
This is the usual way of writing
</font>

## Here we have written only 10 as first argument. NO high or low value was specified. In this case, this method  `my_rng.integers( )` will consider that high value = 10, and assume low value = 0.

## We have seen in lists earlier that `my.list[:4]` is short hand for `my.list[0:4]`.


<font size = 8 color = red face = Monospace>
We often drop the starting value of zero to save repeated typing.
</font>


---
---



## Hence below  
<font size = 8 color = red face = Monospace>
my_rng.integers(10, size = (2,3))
</font>

## ...means from population of numbers from [0,10) draw a sample $ 2 \times 3 = 6$ and place them

## in an array of 2 rows and 3 columns
---
---

In [67]:
rand_2D_T = my_rng.integers(10, size = (2,3))
rand_2D = rand_2D_T #= my_rng.integers(10, size = (2,3))

rand_2D_L = my_rng.integers(10, size = [2,3])
rand_2D_T, rand_2D_L

<IPython.core.display.Javascript object>

(array([[6, 9, 0],
        [7, 5, 8]]),
 array([[8, 1, 7],
        [8, 8, 8]]))

In [68]:
rand_3D = my_rng.integers(6, size = (4, 2, 3))
rand_3D

<IPython.core.display.Javascript object>

array([[[0, 5, 4],
        [3, 1, 5]],

       [[2, 2, 1],
        [1, 4, 5]],

       [[0, 5, 3],
        [2, 5, 1]],

       [[0, 4, 1],
        [1, 5, 5]]])

# We next specify data type if so desired in quotes as `int16`. This will affect how much memory is taken up by the array, compared to say `int64`.

In [69]:
rand_4D = my_rng.integers(20, size = (4, 2, 3, 2), dtype = 'int16')
rand_4D

<IPython.core.display.Javascript object>

array([[[[ 7,  9],
         [ 6,  6],
         [19,  7]],

        [[ 5,  4],
         [12,  3],
         [11,  3]]],


       [[[15, 19],
         [19,  3],
         [13,  7]],

        [[ 9, 17],
         [ 8,  8],
         [17, 16]]],


       [[[12, 11],
         [ 1,  8],
         [10,  7]],

        [[16,  1],
         [ 1,  2],
         [19, 13]]],


       [[[10,  4],
         [11,  4],
         [13, 19]],

        [[ 8, 13],
         [19, 12],
         [16,  1]]]], dtype=int16)

In [70]:
#np.array(dir(rand_1D)).reshape(55,3) # entire list of attributes

<IPython.core.display.Javascript object>

# Important Attributes
- ndim
- shape (IMP: as it is used in pandas also)
- size
- dtype

In [71]:
# @title
print(f'rand_2D dimensions is {rand_2D.ndim}')
print(f'rand_2D shape(rows , cols) is {rand_2D.shape}')
print(f'rand_3D shape(rows , cols) is {rand_3D.shape}')
print(f'rand_4D shape(rows , cols) is {rand_4D.shape}')

<IPython.core.display.Javascript object>

rand_2D dimensions is 2
rand_2D shape(rows , cols) is (2, 3)
rand_3D shape(rows , cols) is (4, 2, 3)
rand_4D shape(rows , cols) is (4, 2, 3, 2)


In [72]:
print(f'rand_3D size(no of elements) is {rand_3D.size}')
print(f'rand_2D data type is {rand_2D.dtype}, Rows is {rand_2D.shape[0]}, Cols is {rand_2D.shape[1]}')

<IPython.core.display.Javascript object>

rand_3D size(no of elements) is 24
rand_2D data type is int64, Rows is 2, Cols is 3


# Working with NumPy `array` : How to Access One Element only
# The similar approach as in lists - we use square brackets
# Indexing of elements starts with 0

In [73]:
rand_2D

<IPython.core.display.Javascript object>

array([[6, 9, 0],
       [7, 5, 8]])

In [74]:
rand_2D[0] # shows up as a array object
type(rand_2D[0]) # confirms doubly that its an array
print(rand_2D[0]) # print to Output
type(print(rand_2D[0])) # drops the array attrib makes it NoneType though it appears like a list
## Why because print directs results to Output and does not store in memory.
## If an object is not stored in memory, python does not need to store its data type.
## So its shows NoneType

<IPython.core.display.Javascript object>

[6 9 0]
[6 9 0]


NoneType

In [75]:
rand_3D

<IPython.core.display.Javascript object>

array([[[0, 5, 4],
        [3, 1, 5]],

       [[2, 2, 1],
        [1, 4, 5]],

       [[0, 5, 3],
        [2, 5, 1]],

       [[0, 4, 1],
        [1, 5, 5]]])

# Indexing from end with [-1] : Last element

In [76]:
rand_3D
rand_3D[-1]


<IPython.core.display.Javascript object>

array([[0, 4, 1],
       [1, 5, 5]])

# In higher dim arrays we can use (row, column, depth) format to extract parts of array
# Recall that indexing starts with 0, So shape (4,2,3) You have to be careful that your indexing is one less than the `my_arr.shape( )` results
# If shape is (4,2,3) indexes can be no more than  [4-1, 2-1, 3-1]

In [77]:
rand_3D
rand_3D.shape # (4,2,3)

<IPython.core.display.Javascript object>

(4, 2, 3)

In [78]:

rand_3D[3,1,1]
# rand_3D[4,1,1] # throws an error
rand_3D[3,1,2] # recall that indexing starts with 0

<IPython.core.display.Javascript object>

np.int64(5)

# We can reset or alter the values of an array using `[  ]` square brackets

In [79]:
rand_2D # before

<IPython.core.display.Javascript object>

array([[6, 9, 0],
       [7, 5, 8]])

In [80]:

rand_2D[0, 1]
rand_2D[0, 1] = 9

<IPython.core.display.Javascript object>

In [81]:

rand_2D # after

<IPython.core.display.Javascript object>

array([[6, 9, 0],
       [7, 5, 8]])

# How to get /access subarrays : Slicing Arrays
## We take an example of


1D array

In [82]:
print(rand_1D)
len(rand_1D) # 7
rand_1D[:4] # Get first four elements -- index 0 to index 3; ie using half-open idea [0, 4)

<IPython.core.display.Javascript object>

[ 6  2  3  4  4  3  7  6  4  8  2  7  4  9  4  7  6 10  3  3  3  7  5 10
  4  3  7  8  2  4  3 10  5  7  8  6  6  5  9 11 10  9  9  6  3 11  8  6
 10  4]


array([6, 2, 3, 4])

In [83]:
rand_1D[2:] # Get all elements after index 2 ie, from index 3 to end
rand_1D[1:4] # Get elements from in beetween using index [1, 4)

<IPython.core.display.Javascript object>

array([2, 3, 4])

# rand[ start: end: step]
<font color = blue size = 14>
rand[ start: end: step]

In [84]:
print(rand_1D)
print(rand_1D [ : : 2]) # every second element
rand_1D [ : : -1] # reverse the order of elements to show. But not in-place; the array itself is not affected
rand_1D [ 3: : -2] # every second element from index 3,  order is reveresed

<IPython.core.display.Javascript object>

[ 6  2  3  4  4  3  7  6  4  8  2  7  4  9  4  7  6 10  3  3  3  7  5 10
  4  3  7  8  2  4  3 10  5  7  8  6  6  5  9 11 10  9  9  6  3 11  8  6
 10  4]
[ 6  3  4  7  4  2  4  4  6  3  3  5  4  7  2  3  5  8  6  9 10  9  3  8
 10]


array([4, 2])

# Working with Higher-Dimensional Arrays

In [85]:
rand_2D
rand_2D [:2, :2] # first two rows ; first 2 columns

<IPython.core.display.Javascript object>

array([[6, 9],
       [7, 5]])

# Caution: Accessing more rows than existing in array, will work without throwing an error
# Use `.shape()` to assess the size of an nD array not index numbers

In [86]:
print(rand_2D)
rand_2D.ndim  # has two rows; this works
rand_2D.shape  # 2,3 which means index of max (1,2) must be used
rand_2D[:2, 0]  # Row[0,2) Col [0] has two rows slicing works
# Surprise
rand_2D[:2, 0].shape  # Extracted array has shape 2 rows in one column, but looks like 1 row 2 columns

<IPython.core.display.Javascript object>

[[6 9 0]
 [7 5 8]]


(2,)

In [87]:
rand_2D[:3, 0]  # has two rows but slicing works, no error
rand_2D[:4, 0]  # has two rows but slicing works, no error

<IPython.core.display.Javascript object>

array([6, 7])

In [88]:
# Let's us generate a larger 2 D array to better show properties
rand_2D1 = my_rng.integers(10, size = (4,5))
print(rand_2D1)

<IPython.core.display.Javascript object>

[[0 4 9 4 5]
 [9 4 0 7 4]
 [0 5 3 4 5]
 [1 9 9 1 3]]


In [89]:

rand_2D1[:2, :3] # Get Rows [0, 2) Cols [0, 3)
rand_2D1[:3, : : 2] # Get All Rows [0, 3) ; Every 2nd column
rand_2D1[::-1, ::-1] # Get All Rows All Columns But in reverse order

<IPython.core.display.Javascript object>

array([[3, 1, 9, 9, 1],
       [5, 4, 3, 5, 0],
       [4, 7, 0, 4, 9],
       [5, 4, 9, 4, 0]])

## Above we have an example of combining Indexing & Slicing for Extraction

In [90]:

print(rand_2D) # recall 2 D Array
rand_2D[: , 0] # get first column, 2D Array hence comma is placed
rand_2D[0 , :] # get first row,   ---ditto---

<IPython.core.display.Javascript object>

[[6 9 0]
 [7 5 8]]


array([6, 9, 0])

# Sub Arrays No Copy Views

In [91]:
my_list_a = [12, 8, 5, 3]
my_list_a


<IPython.core.display.Javascript object>

[12, 8, 5, 3]

In [92]:
my_list_b = my_list_a[:]  # Extract an all element list using slice `[:]`
my_list_b


<IPython.core.display.Javascript object>

[12, 8, 5, 3]

In [93]:
my_list_b == my_list_a  # True -- checks for each element identical or not

my_list_b is my_list_a  # False -- checks if both refer to same object


<IPython.core.display.Javascript object>

False

# Lists produce `copies` when extracted. But numpy arrays return `views`.

## Below rand_2D_A[1,0] is a view. We can use this to assign values to specific elements of the array. One application is a large dataset with say tempearture readings of a warehouse. Assume that temp below zero upto -2 degrees is allowed.

## In case temp sensors are faulty they may hold -9 as a value as a code for the technician for diagnosis. This needs to be modified with with an average value for our analysis.


In [94]:
print(rand_2D)
rand_2D_A = rand_2D

rand_2D_A[1,0] = 3 # we replace value [1,0] with `3`

print (rand_2D_A)

<IPython.core.display.Javascript object>

[[6 9 0]
 [7 5 8]]
[[6 9 0]
 [3 5 8]]


In [95]:
temp_3D = my_rng.integers(20, size = (3, 4, 4), dtype = 'int')
# temp_3D = my_rng.integers(20, size = (3, 4, 4), dtype = 'int')
print(temp_3D)

print(temp_3D[0,1,0] )
temp_3D_sub = temp_3D[0,1,0]
temp_3D_sub = 9
temp_3D_sub #
temp_3D

<IPython.core.display.Javascript object>

[[[ 7 10  9  0]
  [ 8  9  9  2]
  [ 4 14 14 10]
  [ 5  6 10  4]]

 [[18  1  4  1]
  [18 10  7 11]
  [ 3  4  9  3]
  [ 2 17 17 14]]

 [[17 17 18  3]
  [ 7  7 13 13]
  [ 6 13  2  7]
  [16 19 17 14]]]
8


array([[[ 7, 10,  9,  0],
        [ 8,  9,  9,  2],
        [ 4, 14, 14, 10],
        [ 5,  6, 10,  4]],

       [[18,  1,  4,  1],
        [18, 10,  7, 11],
        [ 3,  4,  9,  3],
        [ 2, 17, 17, 14]],

       [[17, 17, 18,  3],
        [ 7,  7, 13, 13],
        [ 6, 13,  2,  7],
        [16, 19, 17, 14]]])

## Below we use `copy()` to avoid over writing any value of the original array

In [96]:
# temp_3D = my_rng.integers(20, size = (3, 4, 4), dtype = 'int')

temp_2D = my_rng.integers(10, size = (2,3))
print(temp_2D)

temp_2D_N = temp_2D[0, 2].copy()
temp_2D_N
temp_2D_N = 5
temp_2D_N

print(f' {temp_2D, temp_2D_N}')

<IPython.core.display.Javascript object>

[[3 7 2]
 [7 6 9]]
 (array([[3, 7, 2],
       [7, 6, 9]]), 5)


## We can also reshape arrays
## Recall np.arange(5, 20) produces an array of 5 to 14 ie, 15 numbers

In [97]:
my_thermo_grid = np.arange(5, 20)
len(my_thermo_grid ) # 15
print(my_thermo_grid )

# 15 numbers must exactly fit in (5,3) array, neither more nor less
np.arange(5, 20).reshape(5,3)

<IPython.core.display.Javascript object>

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

## We use `np.axis` to convert to row array into column array.

In [98]:
my_thermo_grid
my_thermo_grid[np.newaxis, :]
my_thermo_grid[:, np.newaxis]

<IPython.core.display.Javascript object>

array([[ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [99]:
def increase_font():
  from IPython.display import Javascript
  display(Javascript('''
  for (rule of document.styleSheets[0].cssRules){
    if (rule.selectorText=='body') {
      rule.style.fontSize = '30px'
      rule.style.color = 'darkblue'
      break
    }
  }
  '''))
increase_font()
get_ipython().events.register('pre_run_cell', increase_font)
print("Hello in ")
print("...in larger font ")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Hello in 
...in larger font 
