# Numpy offers more efficient storage than List
# An array holds objects of the same type



In [ ]:
# @title
#
# Increase output font size for your audience
#
def increase_font():
  from IPython.display import Javascript
  display(Javascript('''
  for (rule of document.styleSheets[0].cssRules){
    if (rule.selectorText=='body') {
      rule.style.fontSize = '40px'
      rule.style.color = 'blue'
      break
    }
  }
  '''))

increase_font()
get_ipython().events.register('pre_run_cell', increase_font)
print("Hello")

<IPython.core.display.Javascript object>

Hello


In [ ]:
import numpy as np

<IPython.core.display.Javascript object>

#2.1
<font size = 12 color = red>
# If you insert mixed types it will force all elements to be of the same type. Here there is input of one float and rest are integers to nd.array() function. So all other elements are *promoted up* from integers as floats. This is called **upcasting **

In [ ]:
# @title


mxtype_array = np.array([20, 12, 45, 9.86, 43])
mxtype_array

<IPython.core.display.Javascript object>

array([20.  , 12.  , 45.  ,  9.86, 43.  ])

In [ ]:
# @title


np.array([3,7,1,9]) # object is printed by default


<IPython.core.display.Javascript object>

array([3, 7, 1, 9])

In [ ]:
# use this when you dont need to check the object or its type that is being created
np.array([3,7,1,9]); # putting a semicolon supresses output

<IPython.core.display.Javascript object>

<font size = 12>
$$\sum_{i=1}^{n} = J(\theta) $$

In [ ]:
np.array([3,7,1,9] , dtype ='float32') # object can be defined explicity as float, even though we gave integers as input

<IPython.core.display.Javascript object>

array([3., 7., 1., 9.], dtype=float32)

In [ ]:
# @title
arr_3by3 = np.array([range(i, i + 3) for i in (3, 5, 7)])
print(f'This is a 3 by 3 array:\n {arr_3by3}') # note \n is for new line, so output is neater

<IPython.core.display.Javascript object>

This is a 3 by 3 array:
 [[3 4 5]
 [5 6 7]
 [7 8 9]]


# How is this working : Let us examine

```
arr_3by3 = np.array([range(i, i + 3) for i in (3, 5, 7)])
```

$\huge \text{np.array([range(i, i + 3) for i in [3, 5, 7]])}$

In [ ]:
help(range)

<IPython.core.display.Javascript object>

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      True if self else False
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash

In [ ]:

i = 3

r1 = range(i, i + 3)
r1
print(r1)

print(f'This is r1: {r1}')
print (f'This is first row of arr_3by3: {np.array(r1)}')


<IPython.core.display.Javascript object>

range(3, 6)
This is r1: range(3, 6)
This is first row of arr_3by3: [3 4 5]


In [ ]:

i = 5
r2 = range(i, i + 3)
print(r2)
np.array(r2)


<IPython.core.display.Javascript object>

range(5, 8)


array([5, 6, 7])

In [ ]:

i = 7
r3 = range(i, i + 3)
print(r3)
np.array(r3)


<IPython.core.display.Javascript object>

range(7, 10)


array([7, 8, 9])

# Exercise 1.1
# Looking at the code above, create an array called 'arr_4by3' that has 4 rows and 3 columns.
# where will you make the change ?

In [ ]:
# Answer
arr_4by3 = np.array([range(i, i + 4) for i in (3, 5, 7)])
arr_4by3

<IPython.core.display.Javascript object>

array([[ 3,  4,  5,  6],
       [ 5,  6,  7,  8],
       [ 7,  8,  9, 10]])

# We can create arrays from the ground up using built in routines from NumPy

Note how the datatype argument *dtype* is specified without single quotes and with single quotes.
int, float are understood without quotes but,
float32 needs single quotes.

Please try to run each line one by one using CTSL+SHFT+ENTER

In [ ]:
np.zeros(10, dtype = int) # works
np.zeros(10, dtype = 'int') # works
np.zeros(10, dtype = float) # works
np.zeros(10, dtype = 'float') # works
# np.zeros(10, dtype = float32) # but, this throws an error
np.zeros(10, dtype = 'float32') # works


<IPython.core.display.Javascript object>

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

# Next we can create arrays that have a few other elements (other than zero) that are commonly used.

# Application: we can create an array full of zeros. Then after some computation, store that computed value, replacing the zero.

In [ ]:
np.ones(6, dtype = int)
np.ones(6, dtype = float)
# np.ones(6, dtype = float32) # without single quotes, again throws error

<IPython.core.display.Javascript object>

array([1., 1., 1., 1., 1., 1.])

And then we can create an array 3 by 4 with same element 9.8 ($m/s^2$)


In [ ]:
np.full((3,4), 9.8)
np.full((2,2), '9.8 ms^-2') #

<IPython.core.display.Javascript object>

array([['9.8 ms^-2', '9.8 ms^-2'],
       ['9.8 ms^-2', '9.8 ms^-2']], dtype='<U9')

In [ ]:
np.arange(start = 1, stop = 10, step = 2)
np.arange(1,12,2)

<IPython.core.display.Javascript object>

array([ 1,  3,  5,  7,  9, 11])

In [ ]:
np.linspace(0,1,4) # create an array with four values evenly space b/w 0, 1
# np.linspace? # for help

<IPython.core.display.Javascript object>

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
np.random.normal(loc= 0, scale = 5, size = 10)
np.random.normal(loc= 0, scale = 5, size = (2,3)) # an array of random normal

<IPython.core.display.Javascript object>

array([[-0.92815279, -4.36039477, -3.9337967 ],
       [ 0.28361057, -0.3567226 ,  1.45814937]])

# From Stats we know that for a normal distribution we declare the mean and standard deviation.

# Above loc is for location of mean, scale is for standard deviation (how much spread out the data should be)

# In Matrix Theory $I$ stands for Indentity matrix. Where the diagnol element is one and all other elements are zero.   Hence, we can guess that a like-sounding word $np.eye$ is used to avoid a non-distinct, short name like $np.I$



In [ ]:
np.eye(4,4) # create an identity matrix #

<IPython.core.display.Javascript object>

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Attributes
# Let us first create 1-d 2-d 3-d arrays to show their attributes

# Two useful random number generator functions are
  - random.randint : for *integer *
    - these form a *rectangular shaped box*
  - random.normal : for *normally* distributed random numbers
    - these form a *bell* shaped curve

# There are other random distributions also that we may study later courses.

# We set a random seed that gives the same starting point every time we run a piece of code that calls a random function. This way same set of random number will be generated. We have seen this in a previous example. Thus results can be made reproducible.

$\huge \text{create 1D, 2D, 3D arrays called x1, x2, x3}$

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility
x1 = np.random.randint(10, size=6)  # One-dimensional array
x1 # prints the object
print(x1) # only contents printed
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

<IPython.core.display.Javascript object>

[5 0 3 3 7 9]


# The f string format : recently introduced
# Makes print statement output more clear
# Avoids repeated use of quotes and commas

# **Advantage**: everything (text, python object name) in one single quote, no commas

In [ ]:
print("x3 ndim: ", x3.ndim, "# for each piece of text we must use quotes") # given in textbook


<IPython.core.display.Javascript object>

x3 ndim:  3 # for each piece of text we must use quotes


In [ ]:

print(f'x3 has {x3.ndim} dimensions # this uses f string format') # uses f string format single quote makes print more readable


<IPython.core.display.Javascript object>

x3 has 3 dimensions # this uses f string format


In [ ]:

print(f"x3 has {x3.ndim} dimensions") # uses f string format double quote makes print more readable
print(f"x3 has {x3.shape} shape") # uses f string format double quote makes print more readable
print(f"x3 has {x3.size} size") # uses f string format double quote makes print more readable


<IPython.core.display.Javascript object>

x3 has 3 dimensions
x3 has (3, 4, 5) shape
x3 has 60 size


In [ ]:
f'x3 has shape of {x3.shape} data type' #
f'x3 has size of {x3.size} data type' #
f'x3 has {x3.dtype} data type' #

<IPython.core.display.Javascript object>

'x3 has int64 data type'

# Above, if you don't use print(), then all previous lines will be overwritten, only last line will be seen in output.

In [ ]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

<IPython.core.display.Javascript object>

itemsize: 8 bytes
nbytes: 480 bytes


In [ ]:
print(f' x3 has item size of {x3.itemsize} bytes')
print(f' x3 occupies  {x3.nbytes} bytes')


<IPython.core.display.Javascript object>

 x3 has item size of 8 bytes
 x3 occupies  480 bytes


# **Array Indexing**
# By now you have used Python’s standard list indexing and so indexing in NumPy will feel quite familiar.
# In a one-dimensional array, you can access the $i^{th}$  value (counting from zero) by specifying the desired index in square brackets, just as with Python lists.



In [ ]:
x1

<IPython.core.display.Javascript object>

array([5, 0, 3, 3, 7, 9])

In [ ]:
# We must given an index if using square brackets

print(x1) # show for reference

print(x1[0]) # 1st element extracted

print(x1[5]) # 6th element extracted

# print(x1[6]) # referes to the 7th element which doesnt exist in this array, hence error !

f'Note: writing just x[] will throw an error ' # print (x1[])
print(x1)
print (x1[3]) # 4th element extracted
print (x1[4]) # 5th element extracted

<IPython.core.display.Javascript object>

[5 0 3 3 7 9]
5
9
[5 0 3 3 7 9]
3
7


In [ ]:
print(x1)
print(x1[0])
print(x1[-1])

f'placing minus in front of index number is like referring to the logical opposite of start ie, the end. Hence we see {x1[-1]}'

<IPython.core.display.Javascript object>

[5 0 3 3 7 9]
5
9


'placing minus in front of index number is like referring to the logical of opposite of start ie, the end. Hence we see 9'

In [ ]:
print(x1) # printing for quick reference
x1[-2] # print the second element from end

<IPython.core.display.Javascript object>

[5 0 3 3 7 9]


7

## In 2-D array here is how slicing works
## We use commas to separate to $i^{th} $ row and $j^{th} $ column as in matrix theory




In [ ]:
print(x2) # printing for quick reference
print(x2[0,0]) # element first row, first column

<IPython.core.display.Javascript object>

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
3


In [ ]:
print(x2) # printing for quick reference
print(x2[2,0]) # third row first column

<IPython.core.display.Javascript object>

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
1


In [ ]:
print(x2)
print(x2[2,-1]) # third row, and first column from end
print(x2[2,-0]) # third row, placing -minus in front of zero doesn't work - it still means zero
# so element reference is [3,1]

<IPython.core.display.Javascript object>

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
7
1


# Working with parts of an array  : Sub arrays








In [ ]:
print(x2)

<IPython.core.display.Javascript object>

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [ ]:
# 0:2 is a half open interval [0, 2)
x2_sub = x2[:2 , :2]
# This means x2_sub = x2[0:2 , 0:2]

print(x2_sub)


# temp_gt5 = temp[temp>5]

<IPython.core.display.Javascript object>

[[3 5]
 [7 6]]


Of this sub array if we change one element then original array is also changed. Why did this get changed. x2[:2, :2] creates a only view **not a copied (new) object** of the orginal.


In [ ]:
x2_sub[1,1] = 44 # changing one element

x2_sub # resulting array

<IPython.core.display.Javascript object>

array([[ 3,  5],
       [ 7, 44]])

In [ ]:
x2

<IPython.core.display.Javascript object>

array([[ 3,  5,  2,  4],
       [ 7, 44,  8,  8],
       [ 1,  6,  7,  7]])

We see that the change is reflected in the original x2



In [ ]:
np.random.seed(0)  # seed for reproducibility
x4 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
print(x4)

x4_sub_cc = x4[:2,:2].copy()
print(x4_sub_cc)

<IPython.core.display.Javascript object>

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
[[5 0]
 [7 9]]


# Making copies with copy() function preserves the orginal. Which means no changes in the original.

# This becomes useful, when we want to hunt for specific pattern of values that may be mistakes or wrong entries (say, using a logical condition).
# Then we can replace such mistakes very easily working on the sub part of the data.

But using copy() creates a new object without changing the original.


In [ ]:
x4_sub_cc[1,1] = 55
print(x4_sub_cc)
print(x4) # original x4 is preserved

<IPython.core.display.Javascript object>

[[ 5  0]
 [ 7 55]]
[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


# Occassionally, we want to change the shape using reshape()
# Condition is that the number of elements in 1D array must match the number of elements in the 2D array. And vice versa

In [ ]:
x5 = np.arange(1, 10)
print(x5.size)  # 9
print(x5)
x5 = np.arange(1, 10).reshape(3,3) # crecreate 2 D array  3 rows 3 cols
print(x5)


<IPython.core.display.Javascript object>

9
[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:

x5_n = np.arange(1, 10).reshape(3,3)
print(x5_n.size)
print(x5_n)

# x5_wrong = np.arange(1, 10).reshape(3,2) # throws a an error


<IPython.core.display.Javascript object>

9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
x9 = np.array([4,5,6])
x9_n = x9.reshape(3,1) # 3 rows and 1 column; x9 remains the original shape
print(x9_n)

<IPython.core.display.Javascript object>

[[4]
 [5]
 [6]]


But x9 remains as such

In [ ]:

print(x9) # x9 remains the original

<IPython.core.display.Javascript object>

[4 5 6]


Another alternative is to add newaxis

In [ ]:
print(x9)

x9[np.newaxis , :]


<IPython.core.display.Javascript object>

[4 5 6]


array([[4, 5, 6]])

# Joining Arrays : Concatenating

In [ ]:
x = np.array([9, 8, 7])
y = np.array([1, 2, 3])
np.concatenate([x, y])
np.concatenate([y, x]) # order matters


<IPython.core.display.Javascript object>

array([1, 2, 3, 9, 8, 7])

In [ ]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

grid

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid]) # Placed after

<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid, grid], axis = 0) # Placed after axis = 0 is default


<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:

np.concatenate([grid, grid], axis = 1) # Placed interleaved

<IPython.core.display.Javascript object>

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Making a Vertical Stack of elements

In [ ]:
x = np.array([1,2,3]) # 1D array

grid = np.array([[9,8,7],
                [6,5,4]]) # 2D

np.vstack([x, grid])


<IPython.core.display.Javascript object>

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

# Making a Horizontal Stack of elements

In [ ]:
zz = np.array([[99],
               [99]
               ])
print(zz)

<IPython.core.display.Javascript object>

[[99]
 [99]]


In [ ]:
np.hstack([grid, zz])
np.hstack([zz, grid])

<IPython.core.display.Javascript object>

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

Splitting of arrays
Just as concatenating is joining arrays with some functions, we have

np.split
np.hsplit
np.vsplit

Note : We gave two split points, we got three arrays

In [ ]:
 x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

<IPython.core.display.Javascript object>

[1 2 3] [99 99] [3 2 1]


Create a grid object for demo. Then apply hsplit and vplit to it.

In [ ]:
grid = np.arange(16).reshape((4, 4))
grid

<IPython.core.display.Javascript object>

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

<IPython.core.display.Javascript object>

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
